name: React CI

on:
  push:
    branches:
      - "sandbox"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:version: [15.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run test
      - run: npm run build

