name: React CI

on:
  push:
    branches:
      - "sandbox"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      # - uses: jbas1003/bld-app@sandbox
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ serets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: 'us-east-1'     # optional: defaults to us-east-1
      #     SOURCE_DIR: 'build'        # optional: defaults to entire repository

